NAME=libft.a

SOURCE = ft_putchar.c ft_putstr.c ft_putstrstr.c ft_strrev.c ft_strlen.c ft_swap.c ft_isupper.c ft_islower.c  ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strdup.c ft_strcpy.c ft_strncpy.c ft_strcat.c ft_strncat.c ft_strlcat.c ft_strstr.c ft_strnstr.c ft_strcmp.c ft_strncmp.c ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_putnbr.c ft_memalloc.c ft_memdel.c ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_itoa.c ft_putendl.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c  ft_putnbr_fd.c ft_lstnew.c ft_lstdelone.c ft_lstdel.c ft_lstadd.c ft_lstiter.c ft_lstmap.c ft_strcut.c ft_strjoinfree.c ft_strjoinfreefree.c ft_abs.c\
check_wigth.c\
flags.c\
flags_precision.c\
flags_size.c\
flags_zero.c\
ft_error.c\
ft_itoa_base.c\
ft_itoa_baseu.c\
ft_printf.c\
str_s.c\
check_float.c\
ft_pow.c\
multiplyfree.c\
float_round.c\
alternate.c\
filling_minus.c\
filling_without_minus.c\
check_digit.c\
without_dot.c\
negative_digit.c\
create_flags.c\
colors.c\
check_fd.c\
len_less.c\
more_five.c\
free_struct.c\
free_struct_un_float.c\
create_struct.c\
set_type.c\
set_flags.c\
find_width.c\
find_lh.c\
find_stars.c\
read_param.c\
find_end.c\
fill_struct.c\
find_stars_precision.c\
get_next_line.c\

OBJECTS = ${SOURCE:.c=.o}

all: $(NAME)

$(NAME): $(OBJECTS) $(HEADER)
	@ar rc $(NAME) $(OBJECTS)
	@ranlib $(NAME)

$(OBJECTS): %.o : %.c
	@gcc -c $< 

clean:
	@/bin/rm -f $(OBJECTS)

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean all
